CREATE TABLE [TbCategoria](
	[CatId] [int] IDENTITY(1,1) NOT NULL,
	[CatNome] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TbCategoria] PRIMARY KEY CLUSTERED 
(
	[CatId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [TbNoticia](
	[NotId] [int] IDENTITY(1,1) NOT NULL,
	[NotTitulo] [varchar](200) NOT NULL,
	[NotTexto] [text] NOT NULL,
	[NotData] [datetime] NOT NULL,
	[CatId] [int] NOT NULL,
 CONSTRAINT [PK_TbNoticia] PRIMARY KEY CLUSTERED 
(
	[NotId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [TbNoticia]  WITH CHECK ADD  CONSTRAINT [FK_TbNoticia_TbCategoria] FOREIGN KEY([CatId])
REFERENCES [TbCategoria] ([CatId])
GO

ALTER TABLE [TbNoticia] CHECK CONSTRAINT [FK_TbNoticia_TbCategoria]
GO